UserProfile model updated
coderplex-org/coderplex-backend-old pull request #10
Opened 2017-10-30 19:03 UTC by djsbalakrishnan

The user profile model is updated in the member api. Please verify the database structure and suggest changes if required.

2017-10-31 08:09 UTC, rrmerugu requested changes
make the changes accordingly

2017-10-31 08:09 UTC, rrmerugu commented on webapp/member/models.py
> +class Projects(models.Model):
not sure, what we use this for ,  so this task scope is for UserProfile, you can remove this

2017-10-31 08:09 UTC, rrmerugu commented on webapp/member/models.py
> +class Curriculum(models.Model):
not sure, what we use this for ,  so this task scope is for UserProfile, you can remove this

2017-10-31 08:09 UTC, rrmerugu commented on webapp/member/models.py
> +    github_profile = models.URLField(blank=True, null=False, default="", max_length="50")
max_length = 50 ? so you mean to save the user name or id here ?

2017-10-31 08:09 UTC, rrmerugu commented on webapp/member/models.py
> +    discord_username = models.CharField(blank=False, null=False, default="", max_length="25")
why is this "discord_username" if all the above are profile.. make it _profile to keep the consistency

2017-10-31 08:09 UTC, rrmerugu commented on webapp/member/models.py
> +    discord_username = models.CharField(blank=False, null=False, default="", max_length="25")
make null=True, blank=True for all the _profile fields. All need not be mandatory, so all can be null=True(in db it can be null) , blank=True(in form validation it can be null

2017-10-31 08:09 UTC, rrmerugu commented on webapp/member/models.py
> +
Also, write a webhook, the will create UserProfile on user model creation.. should be there in the task descriiption links.. 

ie., when a User model is created (on save for first time), it shall trigger creating profile for that user

2017-10-31 08:09 UTC, rrmerugu commented on webapp/member/models.py
> +    pass
run the makemigrations and push the migration file also..

2017-10-31 08:26 UTC, djsbalakrishnan commented on webapp/member/models.py
> +    github_profile = models.URLField(blank=True, null=False, default="", max_length="50")
No I wanted to store the entire URL with the username. I think 50 should be good because the max length of the URL is 25 characters which is of linkedin [https://www.linkedin.com/]. 

I will anyway increase the URL max_length to 75 so that we have 50 characters just for the username or the ID.

2017-10-31 08:27 UTC, djsbalakrishnan commented on webapp/member/models.py
> +    discord_username = models.CharField(blank=False, null=False, default="", max_length="25")
Will change it.

2017-10-31 08:33 UTC, djsbalakrishnan commented on webapp/member/models.py
> +    discord_username = models.CharField(blank=False, null=False, default="", max_length="25")
According to 2scoops it is best practices to not allow null = True for CharField. I will anyway do this and update the PR.

2017-10-31 14:06 UTC, rrmerugu commented on webapp/member/models.py
> +    discord_username = models.CharField(blank=False, null=False, default="", max_length="25")
Not sure, what is the scenario explained in the 2scoops. But in our case null=True is a way to tell to the backend that, this field can be null in the db.  So in our case, they can be null, so null=True.

2017-10-31 14:08 UTC, rrmerugu requested changes

2017-10-31 14:08 UTC, rrmerugu commented on webapp/member/models.py
you have pushed a lot of *pyc files, webapp/books/__pycache__/__init__.cpython-36.pyc. please clean them, and add *.pyc and __pycache__ to gitignore please

2017-10-31 14:13 UTC, djsbalakrishnan commented
Updated the models as per request. Please validate.

2017-10-31 14:20 UTC, djsbalakrishnan reviewed
Please check the latest commit @rrmerugu

2017-10-31 14:20 UTC, djsbalakrishnan commented on webapp/member/models.py
I did that once I realized I have pushed the compiled binaries. I removed them and committed once more @rrmerugu

2017-10-31 18:42 UTC, rrmerugu commented on webapp/member/models.py
> +    github_profile = models.URLField(blank=True, null=False, default="", max_length="50")
what is job_status and looking for job ?, can you confirm from the requirements ?

2017-11-01 15:18 UTC, rrmerugu approved these changes

2017-11-01 15:18 UTC, rrmerugu commented on webapp/member/models.py
> +    discord_profile = models.CharField(blank=False, null=False, default="", max_length=25)
why is discord blank =False and null=False ? are we forcing people to join discord ? is it part of the requirement

2017-11-01 15:18 UTC, rrmerugu commented
In the UserProfile. discord_profile = models.CharField(blank=False, null=False, default="", max_length=25)   which means discord_profile is mandatory that it cannot be null from the user profile update form . is this what we want ? @duttakapil @vinaypuppal

2017-11-01 15:19 UTC, merged