Social Authentication
coderplex-org/coderplex-backend-old pull request #12
Opened 2017-11-20 20:11 UTC by pbteja1998

- Add Github Social Authentication
- Add Linkedin Social Authentication

2017-11-23 09:16 UTC, rrmerugu commented
@pbteja1998 the code looks clean, im not able to test it locally. Can you make write a change.log with the APIs and features you implemented. And I will merge this.

2017-11-23 10:20 UTC, pbteja1998 commented
@rrmerugu I have added the API end points that I implemented in the Readme, should I add a new file with change.log and write those changes in it too?  Why are you not able to test it locally? What might be the problem?

2017-11-23 10:37 UTC, pbteja1998 commented on webapp/coderplex_apis/settings.py
> +EMAIL_HOST_PASSWORD = ''
@rrmerugu The above settings need to be changed, the email has to be some coderplex email, while testing I filled EMAIL_HOST_PASSWORD with my password and tested it,it works fine. So while hosting you have to create some env variables for these. I don't know how exactly to achieve that, so I left it blank.

2017-11-23 10:37 UTC, pbteja1998 commented on webapp/coderplex_apis/settings.py
> +
I don't know what the above three settings indicate, so I set those with the same values as in the sample app you provided .

2017-11-23 10:37 UTC, pbteja1998 commented on webapp/coderplex_apis/settings.py
I replaced Postgres database with sqlite for convenience. Should I revert back to the way it was before?

2017-11-23 10:37 UTC, pbteja1998 commented on webapp/authentication/views.py
> +    callback_url = "http://127.0.0.1:8000/callback"
A new github and LinkedIn oauth 2.0 coderplex application need to be created with call back URLs as above and those credentials need to be added as social applications  in the Postgres database that we have been using.

2017-11-23 10:37 UTC, pbteja1998 commented on webapp/authentication/serializers.py
> +    code = serializers.CharField(max_length=100)
I don't know exactly where we are using these serializers. I thought it is being used somewhere in the code of django-allauth, if not I will remove it.

2017-11-23 10:48 UTC, pbteja1998 commented on webapp/authentication/views.py
> +    callback_url = "http://127.0.0.1:8000/callback"
After it is hosted, will the base url be automatically resolved or should we change it explicitly with base url of this application in AWS?

2017-11-23 11:30 UTC, rrmerugu commented on webapp/coderplex_apis/settings.py
> +EMAIL_HOST_PASSWORD = ''
hey, why don't you convert  the email and password into os.environ.get('EMAIL_HOST_USER') and os.environ.get('EMAIL_HOST_PASSWORD') . so we can take care of the details while deploying.

2017-11-23 11:33 UTC, rrmerugu commented
@pbteja1998  its not about some code issue, im not to find some time to setup locally and test each component.

2017-11-23 11:35 UTC, rrmerugu commented on webapp/authentication/views.py
> +    callback_url = "http://127.0.0.1:8000/callback"
if callback_url should be in the code, why don't you create it as `LINKEDIN_CALLBACK_URL= os.environ.get("LINKEDIN_CALLBACK_URL ", "https://127.0.0.1:8000/callback")` in `settings.py` , so in the production, we can set LINKEDIN_CALLBACK_URL and it will take that.

2017-11-23 11:36 UTC, rrmerugu commented on webapp/authentication/views.py
> +    callback_url = "http://127.0.0.1:8000/callback"
you should be able to access LINKEDIN_CALLBACK_URL from settings with `from django.conf import settings` and `settings. LINKEDIN_CALLBACK_URL`

2017-11-24 03:31 UTC, pbteja1998 commented on webapp/member/serializers.py
> +        return instance
Is the above implementation correct? Can the update function in serializer take 3 arguments?

2017-11-25 09:44 UTC, rrmerugu requested changes
please make these changes and we are good to merge this PR

2017-11-25 09:46 UTC, rrmerugu approved these changes

2017-11-25 09:49 UTC, rrmerugu requested changes
please make the changes, and I can merge this PR

2017-11-25 09:49 UTC, rrmerugu commented on webapp/member/serializers.py
> +        return instance
use `ModelSerializer` instead of `Serializer`.

2017-11-25 09:49 UTC, rrmerugu commented on webapp/coderplex_apis/settings.py
can we revert this to the Postgres, we can make this config specific to localhost and production settings.  I mean, `localhost.py` uses sqlite3 and `production.py` uses Postgres later

2017-11-25 13:07 UTC, pbteja1998 commented
@rrmerugu I made the requested changes. But User Profile GET, POST apis are not working. I do not know the problem. Can you check it? Other than that Everything is working fine.

2017-11-25 13:40 UTC, pbteja1998 commented on webapp/coderplex_apis/config/production.py
> +
@rrmerugu Is this the correct way for allowing only coderplex?

2017-11-25 13:40 UTC, pbteja1998 commented on webapp/coderplex_apis/config/localhost.py
> +
@rrmerugu Is this the correct way for allowing all hosts?

2017-11-25 15:03 UTC, merged