Configure flake8 Linter and pre-commit
coderplex-org/coderplex-backend-old pull request #22
Opened 2017-11-30 21:23 UTC by vinaypuppal

# What kind of change does this PR introduce
closes #13 

## What is the current behavior
No linter in project

## What is the new behavior
- Configured [Flake8](https://medium.com/python-pandemonium/what-is-flake8-and-why-we-should-use-it-b89bd78073f2) linter
- Added and configured [pre-commit](http://pre-commit.com/) so `flake8` is run for every `git commit`
- Updated `Contributing.md` on how to install `pre-commit` hooks

### Checklist for this PR

* [x] I have read [contributing guidelines](https://github.com/coderplex/coderplex-backend/blob/develop/.github/CONTRIBUTING.md).
* [x] Updated the requirements (`pip freeze > requirements/requirements.txt`). 
* [N/A] Created new migrations (`python webapp/manage.py makemigrations && python webapp/manage.py migrate`).
* [x] Pull request is towards `develop` branch.
* [x] Documentation
* [x] Ready to be merged. 

### Whats missing

- I did not actually fix all linting errors because I am not familiar with whole code base and they are many 😃. When I ran `flake8` I got many lint errors which can found below.
- Travis CI configuration for lint. @pbteja1998 Use [this info](http://pre-commit.com/#usage-in-continuous-integration) for setting up `pre-commit` in travis config

<details>
<summary>Lint Errors</summary>

```
Flake8..............................................................
.....Failedhookid: flake8

webapp/books/tests.py:1:1: F401 'django.test.TestCase' imported but
unused
webapp/authentication/views.py:2:80: E501 line too long (87 > 79 cha
racters)
webapp/authentication/views.py:6:1: F401 'rest_framework.permissions
' imported but unused
webapp/authentication/views.py:8:1: E302 expected 2 blank lines, fou
nd 1webapp/authentication/views.py:13:1: E302 expected 2 blank lines, fo
und 1
webapp/authentication/views.py:16:50: W292 no newline at end of file
webapp/books/urls.py:1:1: F401 'django.conf.urls.include' imported b
ut unused
webapp/books/urls.py:5:1: W293 blank line contains whitespace
webapp/books/urls.py:7:1: W293 blank line contains whitespace
webapp/books/urls.py:9:80: E501 line too long (91 > 79 characters)
webapp/books/urls.py:10:80: E501 line too long (91 > 79 characters)
webapp/books/urls.py:11:1: W293 blank line contains whitespacewebapp/books/urls.py:12:1: W293 blank line contains whitespace
webapp/books/urls.py:15:80: E501 line too long (88 > 79 characters)
webapp/books/urls.py:18:2: W292 no newline at end of file
webapp/books/migrations/0001_initial.py:22:80: E501 line too long (1
14 > 79 characters)
webapp/books/migrations/0001_initial.py:25:80: E501 line too long (9
6 > 79 characters)
webapp/books/migrations/0001_initial.py:29:80: E501 line too long (1
24 > 79 characters)
webapp/books/migrations/0001_initial.py:30:80: E501 line too long (1
54 > 79 characters)
webapp/books/migrations/0001_initial.py:36:80: E501 line too long (1
14 > 79 characters)
webapp/books/migrations/0001_initial.py:40:80: E501 line too long (8
3 > 79 characters)
webapp/books/migrations/0001_initial.py:43:80: E501 line too long (1
31 > 79 characters)
webapp/books/migrations/0001_initial.py:44:80: E501 line too long (1
24 > 79 characters)
webapp/books/migrations/0001_initial.py:45:80: E501 line too long (1
56 > 79 characters)
webapp/books/migrations/0001_initial.py:51:80: E501 line too long (1
14 > 79 characters)
webapp/books/migrations/0001_initial.py:55:80: E501 line too long (8
3 > 79 characters)
webapp/books/migrations/0001_initial.py:58:80: E501 line too long (1
37 > 79 characters)webapp/books/migrations/0001_initial.py:59:80: E501 line too long (1
24 > 79 characters)
webapp/books/migrations/0001_initial.py:60:80: E501 line too long (1
54 > 79 characters)
webapp/coderplex_apis/config/localhost.py:19:63: E231 missing whites
pace after ','
webapp/coderplex_apis/config/localhost.py:19:80: E501 line too long
(96 > 79 characters)
webapp/coderplex_apis/config/localhost.py:20:80: E501 line too long
(93 > 79 characters)
webapp/coderplex_apis/config/localhost.py:20:94: W292 no newline atend of file
webapp/member/models.py:5:1: F401 'django.contrib.auth.login' import
ed but unused
webapp/member/models.py:7:1: E302 expected 2 blank lines, found 1
webapp/member/models.py:14:80: E501 line too long (88 > 79 character
s)
webapp/member/models.py:15:80: E501 line too long (85 > 79 characters)
webapp/member/models.py:17:80: E501 line too long (87 > 79 characters)
webapp/member/models.py:18:80: E501 line too long (82 > 79 characters)
webapp/member/models.py:19:80: E501 line too long (88 > 79 characters)
webapp/member/models.py:20:80: E501 line too long (90 > 79 characters)
webapp/member/models.py:21:80: E501 line too long (89 > 79 characters)
webapp/member/models.py:22:80: E501 line too long (90 > 79 characters)
webapp/member/models.py:23:80: E501 line too long (89 > 79 characters)
webapp/member/models.py:24:80: E501 line too long (90 > 79 characters)
webapp/member/models.py:25:80: E501 line too long (97 > 79 characters)
webapp/member/models.py:26:80: E501 line too long (99 > 79 characters)
webapp/member/models.py:28:1: E302 expected 2 blank lines, found 1
webapp/member/models.py:33:25: E231 missing whitespace after ','
webapp/member/models.py:36:9: F841 local variable 'avatar_url' is assigned to but never used
webapp/member/models.py:37:21: E221 multiple spaces before operator
webapp/member/models.py:56:63: W292 no newline at end of file
webapp/authentication/models.py:1:1: F401 'django.db.models' imported but unused
webapp/authentication/tests.py:1:1: F401 'django.test.TestCase' imported but unused
webapp/member/tests.py:1:1: F401 'django.test.TestCase' imported but unused
webapp/manage.py:14:13: F401 'django' imported but unused
webapp/books/serializers.py:9:1: W293 blank line contains whitespace
webapp/books/serializers.py:14:1: W293 blank line contains whitespace
webapp/books/serializers.py:19:1: W293 blank line contains whitespace
webapp/books/serializers.py:29:1: W293 blank line contains whitespace
webapp/books/serializers.py:39:1: W293 blank line contains whitespace
webapp/books/serializers.py:56:1: W293 blank line contains whitespace
webapp/books/serializers.py:71:1: W293 blank line contains whitespace
webapp/books/serializers.py:72:1: W293 blank line contains whitespace
webapp/books/serializers.py:77:1: W293 blank line contains whitespace
webapp/coderplex_apis/config/production.py:7:18: E201 whitespace after '['
webapp/coderplex_apis/config/production.py:10:1: E265 block commentshould start with '# '
webapp/coderplex_apis/config/production.py:24:60: W292 no newline at end of file
webapp/authentication/serializers.py:3:1: E302 expected 2 blank lines, found 1
webapp/authentication/serializers.py:6:1: E302 expected 2 blank lines, found 1
webapp/authentication/serializers.py:7:49: W292 no newline at end of file
webapp/member/admin.py:4:1: E302 expected 2 blank lines, found 1
webapp/member/admin.py:8:1: E305 expected 2 blank lines after classor function definition, found 1
webapp/member/admin.py:8:54: W292 no newline at end of file
webapp/member/views.py:2:80: E501 line too long (115 > 79 characters)
webapp/member/views.py:8:1: E302 expected 2 blank lines, found 1
webapp/member/views.py:26:1: E302 expected 2 blank lines, found 1
webapp/member/views.py:27:22: E128 continuation line under-indentedfor visual indent
webapp/member/views.py:33:80: E501 line too long (84 > 79 characters)
webapp/member/views.py:38:80: E501 line too long (84 > 79 characters)
webapp/member/views.py:45:47: W292 no newline at end of file
webapp/books/models.py:11:1: W293 blank line contains whitespace
webapp/books/models.py:16:1: W293 blank line contains whitespace
webapp/books/models.py:19:1: W293 blank line contains whitespace
webapp/books/models.py:20:1: W293 blank line contains whitespace
webapp/books/models.py:43:1: W293 blank line contains whitespace
webapp/books/models.py:48:1: W293 blank line contains whitespace
webapp/books/models.py:50:26: W292 no newline at end of file
webapp/books/views.py:1:1: F401 'django.shortcuts.render' importe [...]

2017-11-30 21:33 UTC, vinaypuppal commented
And also I updated `.gitignore` with more generalised ignores for all editors and python recommended ignores

2017-12-01 02:00 UTC, vinaypuppal commented
Just now found [yapf](https://github.com/google/yapf) by google a python code formatter. I configured this with `pre-commit` and lint errors reduced 🎉. 

Below are remaining errors

```
hookid: flake8
webapp/coderplex_apis/config/production.py:10:1: E265 block comment
should start with '# '
webapp/authentication/views.py:2:80: E501 line too long (87 > 79 characters)
webapp/authentication/views.py:6:1: F401 'rest_framework.permissions
' imported but unused
webapp/member/models.py:5:1: F401 'django.contrib.auth.login' import
ed but unused
webapp/member/models.py:50:9: F841 local variable 'avatar_url' is as
signed to but never used
webapp/books/urls.py:1:1: F401 'django.conf.urls.include' imported b
ut unused
webapp/member/views.py:2:80: E501 line too long (115 > 79 characters
)
webapp/manage.py:14:13: F401 'django' imported but unused
webapp/coderplex_apis/settings.py:27:5: F403 'from .config.productio
n import *' used; unable to detect undefined names
webapp/coderplex_apis/settings.py:27:5: F401 '.config.production.*'
imported but unused
webapp/coderplex_apis/settings.py:29:5: F403 'from .config.localhost
 import *' used; unable to detect undefined names
webapp/coderplex_apis/settings.py:29:5: F401 '.config.localhost.*' imported but unused
webapp/coderplex_apis/settings.py:82:80: E501 line too long (83 > 79 characters)
webapp/books/views.py:1:1: F401 'django.shortcuts.render' imported but unused
webapp/books/views.py:7:1: F401 'rest_framework.views.APIView' imported but unused
webapp/books/views.py:10:1: F401 'django.db.models.query.QuerySet' imported but unused
```

2017-12-01 02:13 UTC, vinaypuppal commented
Code Indentation/Formatting changed in PR is default rules set by yapf and above errors are also from default config of flake8.
Both flake8 and yapf can be configured with custom style preferences so check below links and configure as you prefer @pbteja1998 or @rrmerugu 
- http://flake8.pycqa.org/en/latest/
- https://github.com/google/yapf

2017-12-01 03:59 UTC, pbteja1998 commented on .github/CONTRIBUTING.md
> +   ```bash
There is a very small typo in the above line `pre-comm it running`  --> `pre-commit running`

2017-12-01 04:00 UTC, pbteja1998 requested changes

2017-12-01 04:00 UTC, pbteja1998 commented on .github/CONTRIBUTING.md
> +   ```bash
There is a very small typo in the above line `pre-comm it running` --> `pre-commit running`

2017-12-01 04:12 UTC, pbteja1998 submitted a review, later dismissed

2017-12-01 04:16 UTC, pbteja1998 commented
I think this cannot be merged until #21 is merged as it should pull `.travis.yml` for passing the `travis-ci` checks

2017-12-01 04:21 UTC, vinaypuppal commented
@pbteja1998 No need we can ignore status check and merge if this PR is ready to be merged. Actually we need to merge this PR first and fix above lint errors and then configure travis with pre-commit hooks otherwise build will fail due to lint errors.

2017-12-01 04:25 UTC, pbteja1998 approved these changes

2017-12-01 04:26 UTC, pbteja1998 commented
@vinaypuppal How can we ignore status checks, `Merge pull request` button is greyed out as travis-ci has failed.

2017-12-01 04:28 UTC, vinaypuppal commented
@pbteja1998 I just disabled status checks requirements on PR's merging. We can reenable them once we configure travis fully.

2017-12-01 04:31 UTC, merged